### ISSUE TITLE
Error building cppkafka on Windows

### ISSUE THREAD

**Issue by veerarao80** [mfontanini/cppkafka#10]
while compiling with following command I'm getting following errors. How should i solve this issue ?

cmake from visual studio developer tools 15 2017.

commands used:
>cmake .. -DBOOST_INCLUDEDIR="E:\kakfkalib\boost.1.65.1.0\lib\native\include" -DRDKAFKA_LIBRARY="E:\kakfkalib\librdkafka.redist.0.11.0\runtimes\win7-x64\native" -DRDKAFKA_INCLUDE_DIR="E:\kakfkalib\librdkafka.redist.0.11.0\build\native\include"
msbuild.exe ALL_BUILD.vcxproj

Errors:

E:\kakfkalib\cppkafka\build\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj" (default target) (3) ->
(Link target) ->
  backoff_committer.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_message_timestamp [E:\kakfkalib\cpp
kafka\build\src\cppkafka.vcxproj]
  configuration.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_message_timestamp [E:\kakfkalib\cppkafk
a\build\src\cppkafka.vcxproj]
  message.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_message_timestamp [E:\kakfkalib\cppkafka\buil
d\src\cppkafka.vcxproj]
  consumer.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_message_timestamp [E:\kakfkalib\cppkafka\bui
ld\src\cppkafka.vcxproj]
  backoff_performer.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_message_timestamp [E:\kakfkalib\cpp
kafka\build\src\cppkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_new referenced in function "public
: __thiscall cppkafka::Configuration::Configuration(void)" (??0Configuration@cppkafka@@QAE@XZ) [E:\kakfkalib\cppkafka\b
uild\src\cppkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_destroy referenced in function "pr
ivate: static class cppkafka::ClonablePtr<struct rd_kafka_conf_s,void (__cdecl*)(struct rd_kafka_conf_s *),struct rd_ka
fka_conf_s * (__cdecl*)(struct rd_kafka_conf_s const *)> __cdecl cppkafka::Configuration::make_handle(struct rd_kafka_c
onf_s *)" (?make_handle@Configuration@cppkafka@@CA?AV?$ClonablePtr@Urd_kafka_conf_s@@P6AXPAU1@@ZP6APAU1@PBU1@@Z@2@PAUrd
_kafka_conf_s@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_dup referenced in function "privat
e: static class cppkafka::ClonablePtr<struct rd_kafka_conf_s,void (__cdecl*)(struct rd_kafka_conf_s *),struct rd_kafka_
conf_s * (__cdecl*)(struct rd_kafka_conf_s const *)> __cdecl cppkafka::Configuration::make_handle(struct rd_kafka_conf_
s *)" (?make_handle@Configuration@cppkafka@@CA?AV?$ClonablePtr@Urd_kafka_conf_s@@P6AXPAU1@@ZP6APAU1@PBU1@@Z@2@PAUrd_kaf
ka_conf_s@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  producer.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_conf_dup [E:\kakfkalib\cppkafka\build\src\cp
pkafka.vcxproj]
  consumer.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_conf_dup [E:\kakfkalib\cppkafka\build\src\cp
pkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set referenced in function "public
: class cppkafka::Configuration & __thiscall cppkafka::Configuration::set(class std::basic_string<char,struct std::char
_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std
::allocator<char> > const &)" (?set@Configuration@cppkafka@@QAEAAV12@ABV?$basic_string@DU?$char_traits@D@std@@V?$alloca
tor@D@2@@std@@0@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set_dr_msg_cb referenced in functi
on "public: class cppkafka::Configuration & __thiscall cppkafka::Configuration::set_delivery_report_callback(class std:
:function<void __cdecl(class cppkafka::Producer &,class cppkafka::Message const &)>)" (?set_delivery_report_callback@Co
nfiguration@cppkafka@@QAEAAV12@V?$function@$$A6AXAAVProducer@cppkafka@@ABVMessage@2@@Z@std@@@Z) [E:\kakfkalib\cppkafka\
build\src\cppkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set_offset_commit_cb referenced in
 function "public: class cppkafka::Configuration & __thiscall cppkafka::Configuration::set_offset_commit_callback(class
 std::function<void __cdecl(class cppkafka::Consumer &,class cppkafka::Error,class std::vector<class cppkafka::TopicPar
tition,class std::allocator<class cppkafka::TopicPartition> > const &)>)" (?set_offset_commit_callback@Configuration@cp
pkafka@@QAEAAV12@V?$function@$$A6AXAAVConsumer@cppkafka@@VError@2@ABV?$vector@VTopicPartition@cppkafka@@V?$allocator@VT
opicPartition@cppkafka@@@std@@@std@@@Z@std@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set_error_cb referenced in functio
n "public: class cppkafka::Configuration & __thiscall cppkafka::Configuration::set_error_callback(class std::function<v
oid __cdecl(class cppkafka::KafkaHandleBase &,int,class std::basic_string<char,struct std::char_traits<char>,class std:
:allocator<char> > const &)>)" (?set_error_callback@Configuration@cppkafka@@QAEAAV12@V?$function@$$A6AXAAVKafkaHandleBa
se@cppkafka@@HABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z) [E:\kakfkalib\cppkafka\build\
src\cppkafka.vcxproj]
  configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set_throttle_cb referenced in func

**Comment by mfontanini** [comment]
Can you try using `RDKAFKA_ROOT_DIR`? Just point it to the place where the include and lib directories are, that should work. Also I noticed that the document in the Wiki says to do as you did but some user reported that it worked that way, so I'm not sure.

**Comment by veerarao80** [comment]
I tried both below, where rdkafka i downloaded from nuget as per instructions but still getting 90 errors.
I tried to compile myself rdkafka but it too giving some errors. please help.
cmake .. -DBOOST_INCLUDEDIR="E:\kakfkalib\boost.1.65.1.0\lib\native\include" -DRDKAFKA_LIBRARY="E:\kakfkalib\librdkafka.redist.0.11.0\runtimes\win7-x64\native" -DRDKAFKA_INCLUDE_DIR="E:\kakfkalib\librdkafka.redist.0.11.0\build\native\include" -DRDKAFKA_ROOT_DIR="E:\kakfkalib\librdkafka.redist.0.11.0"


cmake .. -DBOOST_INCLUDEDIR="E:\kakfkalib\boost.1.65.1.0\lib\native\include" -DRDKAFKA_LIBRARY="E:\kakfkalib\librdkafka.redist.0.11.0\runtimes\win7-x64\native" -DRDKAFKA_INCLUDE_DIR="E:\kakfkalib\librdkafka.redist.0.11.0\build\native\include" -DRDKAFKA_ROOT_DIR="E:\kakfkalib\librdkafka.redist.0.11.0\runtimes\win7-x86\native"

errors:
in function "public: class cppkafka::TopicConfiguration & __thiscall cppkafka::TopicConfiguration::set_as_opaque(void)"
 (?set_as_opaque@TopicConfiguration@cppkafka@@QAEAAV12@XZ) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  topic_configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_topic_conf_set_partitioner_cb ref
erenced in function "public: class cppkafka::TopicConfiguration & __thiscall cppkafka::TopicConfiguration::set_partitio
ner_callback(class std::function<int __cdecl(class cppkafka::Topic const &,class cppkafka::Buffer const &,int)>)" (?set
_partitioner_callback@TopicConfiguration@cppkafka@@QAEAAV12@V?$function@$$A6AHABVTopic@cppkafka@@ABVBuffer@2@H@Z@std@@@
Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  topic_configuration.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_msg_partitioner_consistent_random
 referenced in function "int __cdecl cppkafka::partitioner_callback_proxy(struct rd_kafka_topic_s const *,void const *,
unsigned int,int,void *,void *)" (?partitioner_callback_proxy@cppkafka@@YAHPBUrd_kafka_topic_s@@PBXIHPAX2@Z) [E:\kakfka
lib\cppkafka\build\src\cppkafka.vcxproj]
  topic.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_topic_partition_available referenced in functio
n "public: bool __thiscall cppkafka::Topic::is_partition_available(int)const " (?is_partition_available@Topic@cppkafka@
@QBE_NH@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  topic.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_topic_destroy referenced in function "public: _
_thiscall cppkafka::Topic::Topic(struct rd_kafka_topic_s *)" (??0Topic@cppkafka@@QAE@PAUrd_kafka_topic_s@@@Z) [E:\kakfk
alib\cppkafka\build\src\cppkafka.vcxproj]
  message.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_message_destroy referenced in function "publi
c: __thiscall cppkafka::Message::Message(struct rd_kafka_message_s *)" (??0Message@cppkafka@@QAE@PAUrd_kafka_message_s@
@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  topic_partition_list.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_topic_partition_list_new referen
ced in function "class std::unique_ptr<struct rd_kafka_topic_partition_list_s,void (__cdecl*)(struct rd_kafka_topic_par
tition_list_s *)> __cdecl cppkafka::convert(class std::vector<class cppkafka::TopicPartition,class std::allocator<class
 cppkafka::TopicPartition> > const &)" (?convert@cppkafka@@YA?AV?$unique_ptr@Urd_kafka_topic_partition_list_s@@P6AXPAU1
@@Z@std@@ABV?$vector@VTopicPartition@cppkafka@@V?$allocator@VTopicPartition@cppkafka@@@std@@@3@@Z) [E:\kakfkalib\cppkaf
ka\build\src\cppkafka.vcxproj]
  topic_partition_list.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_topic_partition_list_destroy ref
erenced in function "class std::unique_ptr<struct rd_kafka_topic_partition_list_s,void (__cdecl*)(struct rd_kafka_topic
_partition_list_s *)> __cdecl cppkafka::convert(class std::vector<class cppkafka::TopicPartition,class std::allocator<c
lass cppkafka::TopicPartition> > const &)" (?convert@cppkafka@@YA?AV?$unique_ptr@Urd_kafka_topic_partition_list_s@@P6AX
PAU1@@Z@std@@ABV?$vector@VTopicPartition@cppkafka@@V?$allocator@VTopicPartition@cppkafka@@@std@@@3@@Z) [E:\kakfkalib\cp
pkafka\build\src\cppkafka.vcxproj]
  topic_partition_list.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_topic_partition_list_add referen
ced in function "class std::unique_ptr<struct rd_kafka_topic_partition_list_s,void (__cdecl*)(struct rd_kafka_topic_par
tition_list_s *)> __cdecl cppkafka::convert(class std::vector<class cppkafka::TopicPartition,class std::allocator<class
 cppkafka::TopicPartition> > const &)" (?convert@cppkafka@@YA?AV?$unique_ptr@Urd_kafka_topic_partition_list_s@@P6AXPAU1
@@Z@std@@ABV?$vector@VTopicPartition@cppkafka@@V?$allocator@VTopicPartition@cppkafka@@@std@@@3@@Z) [E:\kakfkalib\cppkaf
ka\build\src\cppkafka.vcxproj]
  metadata.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_metadata_destroy referenced in function "pub
lic: __thiscall cppkafka::Metadata::Metadata(struct rd_kafka_metadata const *)" (??0Metadata@cppkafka@@QAE@PBUrd_kafka_
metadata@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  group_information.obj : error LNK2019: unresolved external symbol __imp__ntohl@4 referenced in function "public: __th
iscall cppkafka::MemberAssignmentInformation::MemberAssignmentInformation(class std::vector<unsigned char,class std::al
locator<unsigned char> > const &)" (??0MemberAssignmentInformation@cppkafka@@QAE@ABV?$vector@EV?$allocator@E@std@@@std@
@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  group_information.obj : error LNK2019: unresolved external symbol __imp__ntohs@4 referenced in function "public: __th
iscall cppkafka::MemberAssignmentInformation::MemberAssignmentInformation(class std::vector<unsigned char,class std::al
locator<unsigned char> > const &)" (??0MemberAssignmentInformation@cppkafka@@QAE@ABV?$vector@EV?$allocator@E@std@@@std@
@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  error.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_err2str referenced in function "public: class s
td::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall cppkafka::Error::to_string(
void)const " (?to_string@Error@cppkafka@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [E:\kak
fkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_errno2err referenced in function "p
rivate: class cppkafka::Topic __thiscall cppkafka::KafkaHandleBase::get_topic(class std::basic_string<char,struct std::
char_traits<char>,class std::allocator<char> > const &,struct rd_kafka_topic_conf_s *)" (?get_topic@KafkaHandleBase@cpp
kafka@@AAE?AVTopic@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAUrd_kafka_topic_conf_s@@@Z) [E:\
kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set_default_topic_conf referen
ced in function "protected: __thiscall cppkafka::KafkaHandleBase::KafkaHandleBase(class cppkafka::Configuration)" (??0K
afkaHandleBase@cppkafka@@IAE@VConfiguration@1@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_destroy referenced in function "pro
tected: void __thiscall cppkafka::KafkaHandleBase::set_handle(struct rd_kafka_s *)" (?set_handle@KafkaHandleBase@cppkaf
ka@@IAEXPAUrd_kafka_s@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_name referenced in function "public
: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall cppkafka::KafkaHan
dleBase::get_name(void)const " (?get_name@KafkaHandleBase@cppkafka@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allo
cator@D@2@@std@@XZ) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_topic_new referenced in function "p
rivate: class cppkafka::Topic __thiscall cppkafka::KafkaHandleBase::get_topic(class std::basic_string<char,struct std::
char_traits<char>,class std::allocator<char> > const &,struct rd_kafka_topic_conf_s *)" (?get_topic@KafkaHandleBase@cpp
kafka@@AAE?AVTopic@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAUrd_kafka_topic_conf_s@@@Z) [E:\
kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_pause_partitions referenced in func
tion "public: void __thiscall cppkafka::KafkaHandleBase::pause_partitions(class std::vector<class cppkafka::TopicPartit
ion,class std::allocator<class cppkafka::TopicPartition> > const &)" (?pause_partitions@KafkaHandleBase@cppkafka@@QAEXA
BV?$vector@VTopicPartition@cppkafka@@V?$allocator@VTopicPartition@cppkafka@@@std@@@std@@@Z) [E:\kakfkalib\cppkafka\buil
d\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_resume_partitions referenced in fun
ction "public: void __thiscall cppkafka::KafkaHandleBase::resume_partitions(class std::vector<class cppkafka::TopicPart
ition,class std::allocator<class cppkafka::TopicPartition> > const &)" (?resume_partitions@KafkaHandleBase@cppkafka@@QA
EXABV?$vector@VTopicPartition@cppkafka@@V?$allocator@VTopicPartition@cppkafka@@@std@@@std@@@Z) [E:\kakfkalib\cppkafka\b
uild\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_query_watermark_offsets referenced
in function "public: class std::tuple<__int64,__int64> __thiscall cppkafka::KafkaHandleBase::query_offsets(class cppkaf
ka::TopicPartition const &)const " (?query_offsets@KafkaHandleBase@cppkafka@@QBE?AV?$tuple@_J_J@std@@ABVTopicPartition@
2@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_offsets_for_times referenced in fun
ction "public: class std::vector<class cppkafka::TopicPartition,class std::allocator<class cppkafka::TopicPartition> >
__thiscall cppkafka::KafkaHandleBase::get_offsets_for_times(class std::map<class cppkafka::TopicPartition,class std::ch
rono::duration<__int64,struct std::ratio<1,1000> >,struct std::less<class cppkafka::TopicPartition>,class std::allocato
r<struct std::pair<class cppkafka::TopicPartition const ,class std::chrono::duration<__int64,struct std::ratio<1,1000>
> > > > const &)const " (?get_offsets_for_times@KafkaHandleBase@cppkafka@@QBE?AV?$vector@VTopicPartition@cppkafka@@V?$a
llocator@VTopicPartition@cppkafka@@@std@@@std@@ABV?$map@VTopicPartition@cppkafka@@V?$duration@_JU?$ratio@$00$0DOI@@std@
@@chrono@std@@U?$less@VTopicPartition@cppkafka@@@5@V?$allocator@U?$pair@$$CBVTopicPartition@cppkafka@@V?$duration@_JU?$
ratio@$00$0DOI@@std@@@chrono@std@@@std@@@5@@4@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_metadata referenced in function "pr
ivate: class cppkafka::Metadata __thiscall cppkafka::KafkaHandleBase::get_metadata(bool,struct rd_kafka_topic_s *)const
 " (?get_metadata@KafkaHandleBase@cppkafka@@ABE?AVMetadata@2@_NPAUrd_kafka_topic_s@@@Z) [E:\kakfkalib\cppkafka\build\sr
c\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_list_groups referenced in function
"private: class std::vector<class cppkafka::GroupInformation,class std::allocator<class cppkafka::GroupInformation> > _
_thiscall cppkafka::KafkaHandleBase::fetch_consumer_groups(char const *)" (?fetch_consumer_groups@KafkaHandleBase@cppka
fka@@AAE?AV?$vector@VGroupInformation@cppkafka@@V?$allocator@VGroupInformation@cppkafka@@@std@@@std@@PBD@Z) [E:\kakfkal
ib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_group_list_destroy referenced in fu
nction "private: class std::vector<class cppkafka::GroupInformation,class std::allocator<class cppkafka::GroupInformati
on> > __thiscall cppkafka::KafkaHandleBase::fetch_consumer_groups(char const *)" (?fetch_consumer_groups@KafkaHandleBas
e@cppkafka@@AAE?AV?$vector@VGroupInformation@cppkafka@@V?$allocator@VGroupInformation@cppkafka@@@std@@@std@@PBD@Z) [E:\
kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_brokers_add referenced in function
"public: void __thiscall cppkafka::KafkaHandleBase::add_brokers(class std::basic_string<char,struct std::char_traits<ch
ar>,class std::allocator<char> > const &)" (?add_brokers@KafkaHandleBase@cppkafka@@QAEXABV?$basic_string@DU?$char_trait
s@D@std@@V?$allocator@D@2@@std@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  kafka_handle_base.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_outq_len referenced in function "pu
blic: int __thiscall cppkafka::KafkaHandleBase::get_out_queue_length(void)const " (?get_out_queue_length@KafkaHandleBas
e@cppkafka@@QBEHXZ) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  producer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set_opaque referenced in function "publ
ic: __thiscall cppkafka::Producer::Producer(class cppkafka::Configuration)" (??0Producer@cppkafka@@QAE@VConfiguration@1
@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_conf_set_opaque [E:\kakfkalib\cppkafka\build
\src\cppkafka.vcxproj]
  producer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_new referenced in function "public: __thisca
ll cppkafka::Producer::Producer(class cppkafka::Configuration)" (??0Producer@cppkafka@@QAE@VConfiguration@1@@Z) [E:\kak
fkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2001: unresolved external symbol __imp__rd_kafka_new [E:\kakfkalib\cppkafka\build\src\cppkafk
a.vcxproj]
  producer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_poll referenced in function "public: int __t
hiscall cppkafka::Producer::poll(class std::chrono::duration<__int64,struct std::ratio<1,1000> >)" (?poll@Producer@cppk
afka@@QAEHV?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  producer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_producev referenced in function "public: voi
d __thiscall cppkafka::Producer::produce(class cppkafka::MessageBuilder const &)" (?produce@Producer@cppkafka@@QAEXABVM
essageBuilder@2@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  producer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_flush referenced in function "public: void _
_thiscall cppkafka::Producer::flush(class std::chrono::duration<__int64,struct std::ratio<1,1000> >)" (?flush@Producer@
cppkafka@@QAEXV?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  producer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_set_log_level referenced in function "public
: __thiscall cppkafka::Producer::Producer(class cppkafka::Configuration)" (??0Producer@cppkafka@@QAE@VConfiguration@1@@
Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_last_error referenced in function __catch$??
1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_conf_set_rebalance_cb referenced in function
 "public: __thiscall cppkafka::Consumer::Consumer(class cppkafka::Configuration)" (??0Consumer@cppkafka@@QAE@VConfigura
tion@1@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_memberid referenced in function __catch$??1C
onsumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_get_watermark_offsets referenced in function
 __catch$??1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_queue_get_consumer referenced in function __
catch$??1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_consume_batch_queue referenced in function _
_catch$??1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_subscribe referenced in function __catch$??1
Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_unsubscribe referenced in function __catch$?
?1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_subscription referenced in function __catch$
??1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_consumer_poll referenced in function __catch
$??1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_consumer_close referenced in function __catc
h$??1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_assign referenced in function __catch$??1Con
sumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_assignment referenced in function __catch$??
1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_commit referenced in function __catch$??1Con
sumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_commit_message referenced in function __catc
h$??1Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_committed referenced in function __catch$??1
Consumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_position referenced in function __catch$??1C
onsumer@cppkafka@@UAE@XZ$0 [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  consumer.obj : error LNK2019: unresolved external symbol __imp__rd_kafka_poll_set_consumer referenced in function "pu
blic: __thiscall cppkafka::Consumer::Consumer(class cppkafka::Configuration)" (??0Consumer@cppkafka@@QAE@VConfiguration
@1@@Z) [E:\kakfkalib\cppkafka\build\src\cppkafka.vcxproj]
  E:\kakfkalib\cppkafka\build\src\Debug\cppkafka.dll : fatal error LNK1120: 74 unresolved externals [E:\kakfkalib\cppka
fka\build\src\cppkafka.vcxproj]

    0 Warning(s)
    90 Error(s)

Time Elapsed 00:00:01.00

E:\kakfkalib\cppkafka\build>

**Comment by mfontanini** [comment]
I managed to build it as a static library by adding `-DCPPKAFKA_BUILD_SHARED=0`. Still checking on the shared build now.

**Comment by Mandy27** [comment]
Have you fixed this issue yet? I am having the same problem when I build it as static library.

**Comment by mfontanini** [comment]
I still haven't fixed this. I would appreciate the help though, the code isn't doing anything weird so I'm not sure if this is caused by the way rdkafka is built on the redistributable binaries for Windows.

**Comment by mmatvien** [comment]
Same problem here. Is there a resolution?

**Comment by yorkhellen** [comment]
Same problem here.

**Comment by shane151** [comment]
Same issue here building the shared lib. Builds works fine as a static lib.

**Comment by mfontanini** [comment]
So I finally installed a proper Windows setup and managed to build this as a shared lib. The main issue was that the CMake invocation as shown in the first message is trying to link against a directory rather than the rdkafka library. What worked for me was:

**Comment by mfontanini** [comment]
So I finally installed a proper Windows setup and managed to build this as a shared lib. The main issue was that the CMake invocation as shown in the first message is trying to link against a directory rather than the rdkafka library. What worked for me was:

* Download librdkafka's source and build it using cmake (this works great).
* Download cppkafka and build it but when you provide the `RDKAFKA_LIBRARY` parameter, make it point to the actual .lib file. e.g. `C:\\some\path\librdkafka\debug\rdkafka.lib`

I just pushed a tiny fix because apparently you need to link against ws2_32.lib on Windows to use `ntohs`. Can someone pull from master and confirm if this works for them as well?

**Comment by yorkhellen** [comment]
Still not work. 2 link errors

command:
cmake . -DRDKAFKA_LIBRARY="C:\Users\york\Desktop\librdkafka-master\win32\outdir\v140\x64\Debug\librdkafka.lib" 

result:
1>group_information.obj : error LNK2019: unresolved external symbol __imp_ntohl referenced in function "public: __cdecl cppkafka::MemberAssignmentInformation::MemberAssignmentInformation(class std::vector<unsigned char,class std::allocator<unsigned char> > const &)" (??0MemberAssignmentInformation@cppkafka@@QEAA@AEBV?$vector@EV?$allocator@E@std@@@std@@@Z)
1>group_information.obj : error LNK2019: unresolved external symbol __imp_ntohs referenced in function "public: __cdecl cppkafka::MemberAssignmentInformation::MemberAssignmentInformation(class std::vector<unsigned char,class std::allocator<unsigned char> > const &)" (??0MemberAssignmentInformation@cppkafka@@QEAA@AEBV?$vector@EV?$allocator@E@std@@@std@@@Z)
1>C:\Users\york\Desktop\cppkafka-master\x64\Debug\cppkafka.dll : fatal error LNK1120: 2 unresolved externals
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by mfontanini** [comment]
Did you, as I mentioned in my comment, pull from master? Because that's the error I fixed on my last commit.

**Comment by yorkhellen** [comment]
I just pull from the master, it's work.
2>  cppkafka.vcxproj -> D:\code\ckafka\cppkafka-master\x64\Debug\cppkafka.dll
2>  cppkafka.vcxproj -> D:/code/ckafka/cppkafka-master/src/Debug/cppkafka.pdb (Full PDB)
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by zyercan** [comment]
Hi all. I was also able to generate cppkafka.dll. My setup is Windows10 (10.0.14393) using a SDK ver. 10.0.16299.0 with VS 15 (2017) and MSVC 19.13.26128.0

However, when I tried to run a simple producer code (given in readme.md), I have dozens of error (C2491) which is originated from message_builder.h. Do you have any idea???
I wrote to the additional include directories section of the include paths of cppkafka, librdkafka and boost headers.
Also I have included the additional library directories of cppkafka.lib
And I wrote cppkafka.lib to the Additional Dependencies in my VS setup.

C2491 'cppkafka::BasicMessageBuilder<BufferType,Concrete>::BasicMessageBuilder': definition of dllimport function not allowed.

**Comment by mfontanini** [comment]
Ugh why is windows so hard? I can have a look at this tonight but in the meantime, could you try editting message_builder.h and remove the CPPKAFKA_API macro from the class definition? e.g. so it looks like this:
```c++
cltemplate <typename BufferType, typename Concrete>
ass BasicMessageBuilder {
```

And see if at least you don't see any error messages regarding `BasicMessageBuilder`?

**Comment by zyercan** [comment]
I have just tried your solution. Looks like I got rid of that error but now there is a new one. 
Any ideas?? damn you windows!!
 
LNK2019	unresolved external symbol "public: __thiscall cppkafka::ConfigurationOption::ConfigurationOption(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,char const *)" (??0ConfigurationOption@cppkafka@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD@Z)

**Comment by zyercan** [comment]
I found the problem. It was caused by the class ConfigurationOption. I just put the dll macro CPPKAFKA_API  (class CPPKAFKA_API ConfigurationOption) and now it builds and works fine!

**Comment by mfontanini** [comment]
Oh yeah, thanks for checking that. I just pushed a fix for this, can you confirm if you can use `master` and everything works as expected? If so, I'll close this issue.

**Comment by zyercan** [comment]
I have built it from master and it is working!

**Comment by mfontanini** [comment]
Nice, I'll update the docs regarding building on windows on the wiki tonight. Thanks!

**Comment by mfontanini** [comment]
One more question: are you using the nuget packages for librdkafka or did you build it from source?

**Comment by zyercan** [comment]
I am building the librdkafka from the source by using cmake. Also I have downloaded boost from its website. So I didn't use any NuGet packages.

**Comment by mfontanini** [comment]
No problem, I imagine this should work either way. Thanks!

**Comment by latermarch** [comment]
![image](https://user-images.githubusercontent.com/9695216/60429299-61378280-9c2d-11e9-8645-5731098cba5d.png)
I meet a quesetion,just in the pic bellow,when I delete the function "swap_queues", the producer example works well

**Comment by latermarch** [comment]
anyone helps ?

**Comment by latermarch** [comment]
![image](https://user-images.githubusercontent.com/9695216/60449764-ef762d80-9c5a-11e9-8b94-b8f34be74aab.png)
any one can help me ?

**Comment by steinio** [comment]
Hi. I see that this is a year old issue, but I am encountering the very same issue described at the top.
I get hundreds of these errors:

cppkafka-master\out\install\x64-Debug\include\cppkafka/utils/buffered_producer.h(579): error C2491: 'cppkafka::BufferedProducer<BufferType,Allocator>::BufferedProducer': definition of dllimport function not allowed

I am using visual studio 2019 with the 2015 build tools and 10.0.17763.0 target platform.
I have used the latest tags for both librdkafka and cppkafka, as well as the masters and librdkafka's nuget package, but I get the same error no matter what.  Any advice?

These are the latest cmake flags used for my attempt with master librdkafka built myself:

CPPKAFKA_BOOST_STATIC_LIBS = TRUE
CPPKAFKA_BUILD_SHARED = TRUE
RDKAFKA_INCLUDE_DIR = C:/Libs/librdkafka-1.1.0/out/install/x64-Debug/include
RDKAFKA_LIBRARY = C:/Libs/librdkafka-1.1.0/out/install/x64-Debug/lib/rdkafka.lib

I have also tried with the top flags set to false, with no change.

**Comment by latermarch** [comment]
> Hi. I see that this is a year old issue, but I am encountering the very same issue described at the top.
> I get hundreds of these errors:
> 
> cppkafka-master\out\install\x64-Debug\include\cppkafka/utils/buffered_producer.h(579): error C2491: 'cppkafka::BufferedProducer<BufferType,Allocator>::BufferedProducer': definition of dllimport function not allowed
> 
> I am using visual studio 2019 with the 2015 build tools and 10.0.17763.0 target platform.
> I have used the latest tags for both librdkafka and cppkafka, as well as the masters and librdkafka's nuget package, but I get the same error no matter what. Any advice?
> 
> These are the latest cmake flags used for my attempt with master librdkafka built myself:
> 
> CPPKAFKA_BOOST_STATIC_LIBS = TRUE
> CPPKAFKA_BUILD_SHARED = TRUE
> RDKAFKA_INCLUDE_DIR = C:/Libs/librdkafka-1.1.0/out/install/x64-Debug/include
> RDKAFKA_LIBRARY = C:/Libs/librdkafka-1.1.0/out/install/x64-Debug/lib/rdkafka.lib
> 
> I have also tried with the top flags set to false, with no change.

hi ,we meet the same issus, And I can't figured it out yet,  do you figure it out?

**Comment by latermarch** [comment]
@steinio  hi ,we meet the same issus, And I can't figured it out yet, do you figure it out?

**Comment by steinio** [comment]
No, I posted this yesterday, so not much has changed unfortunately. I am a novice when it comes to Visual Studio, and I think that my issue might just be in how I set up my project or how I built the libraries with cmake in visual studio 2019. Maybe I am missing something obvious.

**Comment by steinio** [comment]
My error is not the same I realize, I mixed it up with another issue, but here is my error:

error C2491: 'cppkafka::BufferedProducer<BufferType,Allocator>::BufferedProducer': definition of dllimport function not allowed

And this goes on for some other files aswell

**Comment by steinio** [comment]
@latermarch I just noticed your post about this today, and this solved it for me, thanks.
